"""Add analytics PageHit model

Revision ID: c43e773a034b
Revises: 18f4f362b5be
Create Date: 2026-02-06 16:20:35.121348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c43e773a034b'
down_revision = '18f4f362b5be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_hits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('visitor_hash', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=50), nullable=True),
    sa.Column('os', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_hits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_hits_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_hits_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_hits_visitor_hash'), ['visitor_hash'], unique=False)

    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscribers_email'))

    op.drop_table('subscribers')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        # batch_op.alter_column('content',
        #        existing_type=postgresql.JSON(astext_type=sa.Text()),
        #        type_=postgresql.JSONB(astext_type=sa.Text()),
        #        existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        # batch_op.alter_column('tags',
        #        existing_type=postgresql.JSON(astext_type=sa.Text()),
        #        type_=postgresql.ARRAY(sa.String()),
        #        existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_article_published_at'))
        batch_op.drop_index(batch_op.f('idx_article_slug'))
        batch_op.drop_index(batch_op.f('idx_article_status'))
        batch_op.create_index(batch_op.f('ix_articles_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_status'))
        batch_op.drop_index(batch_op.f('ix_articles_published_at'))
        batch_op.create_index(batch_op.f('idx_article_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_article_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('idx_article_published_at'), ['published_at'], unique=False)
        # batch_op.alter_column('tags',
        #        existing_type=postgresql.ARRAY(sa.String()),
        #        type_=postgresql.JSON(astext_type=sa.Text()),
        #        existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        # batch_op.alter_column('content',
        #        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        #        type_=postgresql.JSON(astext_type=sa.Text()),
        #        existing_nullable=True)

    op.create_table('subscribers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('subscribers_pkey'))
    )
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscribers_email'), ['email'], unique=True)

    with op.batch_alter_table('page_hits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_hits_visitor_hash'))
        batch_op.drop_index(batch_op.f('ix_page_hits_timestamp'))
        batch_op.drop_index(batch_op.f('ix_page_hits_path'))

    op.drop_table('page_hits')
    # ### end Alembic commands ###
